:: Generated by clanker

@echo off
setlocal enabledelayedexpansion

set "SCRIPT_DIR=%~dp0"
set "VCVARS="

for /f "usebackq delims=" %%i in (`
  "%ProgramFiles(x86)%\Microsoft Visual Studio\Installer\vswhere.exe" ^
    -latest -products * ^
    -requires Microsoft.VisualStudio.Component.VC.Tools.x86.x64 ^
    -find VC\Auxiliary\Build\vcvars64.bat
`) do set "VCVARS=%%i"

if not defined VCVARS (
  echo Could not find Visual Studio C++ build tools.
  exit /b 1
)

call "%VCVARS%" >nul
powershell -NoProfile -ExecutionPolicy Bypass -File "%SCRIPT_DIR%test.ps1"
